/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 9b973207369b88eaf1aa9615992f5b95)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "EnrollmentAgent";
	}
	interface Env {
		AI: Ai;
		EnrollmentAgent: DurableObjectNamespace<import("./src/server").EnrollmentAgent>;
	}
}
interface Env extends Cloudflare.Env {}
